**Logistic Regression** - An algorithm used for categorical value prediction

In [ ]:
import numpy as np
data = np.array([[3.87,2.65,0],
                 [2.64,3.63,0],
                 [4.93,5.50,0],
                 [2.83,2.95,0],
                 [4.07,4.00,0],
                 [8.27,3.57,1],
                 [6.36,3.09,1],
                 [7.99,2.97,1],
                 [9.76,1.42,1],
                 [8.76,4.60,1]])
print(data)

[[3.87 2.65 0.  ]
 [2.64 3.63 0.  ]
 [4.93 5.5  0.  ]
 [2.83 2.95 0.  ]
 [4.07 4.   0.  ]
 [8.27 3.57 1.  ]
 [6.36 3.09 1.  ]
 [7.99 2.97 1.  ]
 [9.76 1.42 1.  ]
 [8.76 4.6  1.  ]]
[[3.87 2.65 0.  ]
 [2.64 3.63 0.  ]
 [4.93 5.5  0.  ]
 [2.83 2.95 0.  ]
 [4.07 4.   0.  ]
 [8.27 3.57 1.  ]
 [6.36 3.09 1.  ]
 [7.99 2.97 1.  ]
 [9.76 1.42 1.  ]
 [8.76 4.6  1.  ]]

In [ ]:
from math import exp

def predict_val(data_row,coef):
  yh = coef[0] + coef[1] * data_row[0] + coef[2] * data_row[1]
  return 1 / (1 + exp(-yh))

In [ ]:
coef = [0.9,0.8,1.1]

for row in data:
  print(row[2] , predict_val(row,coef), round(predict_val(row,coef)))

0.0 0.9990042320048416 1
0.0 0.9990934885733027 1
0.0 0.9999814310284996 1
0.0 0.9983560367162356 1
0.0 0.9998076496999406 1
1.0 0.9999892758325609 1
1.0 0.9999162005239588 1
1.0 0.9999740418766412 1
1.0 0.9999653438256669 1
1.0 0.9999976661757664 1
0.0 0.9990042320048416 1
0.0 0.9990934885733027 1
0.0 0.9999814310284996 1
0.0 0.9983560367162356 1
0.0 0.9998076496999406 1
1.0 0.9999892758325609 1
1.0 0.9999162005239588 1
1.0 0.9999740418766412 1
1.0 0.9999653438256669 1
1.0 0.9999976661757664 1

In [ ]:
#Stocastic gradient descent

for iter in range(500):
  sum_error = 0
  for row in data:
    #error = y - z
    z = predict_val(row,coef)
    error = row[2] - z
    sum_error += error**2

    lr = 1

    #grad = -2 * (y-z) * z * (1-z) * x
    #w = w - lr * de/dw

    coef[0] = coef[0] - lr * (-2 * error * z * (1-z))
    coef[1] = coef[1] - lr * (-2 * error * z * (1-z) * row[0])
    coef[2] = coef[2] - lr * (-2 * error * z * (1-z) * row[1])

  print(iter,sum_error)

0 4.9920656591522965
1 4.9905722478260195
2 4.988387790886223
3 4.984889976735901
4 4.978387918367483
5 4.962040322131133
6 5.058997945156312
7 4.999639925453628
8 4.999637384313639
9 4.999634806938728
10 4.999632192547506
11 4.999629540335944
12 4.999626849476545
13 4.999624119117483
14 4.999621348381703
15 4.99961853636598
16 4.9996156821399325
17 4.9996127847449925
18 4.999609843193338
19 4.999606856466757
20 4.999603823515481
21 4.999600743256945
22 4.999597614574496
23 4.999594436316044
24 4.999591207292641
25 4.999587926277004
26 4.999584592001944
27 4.999581203158736
28 4.999577758395406
29 4.9995742563149275
30 4.9995706954733246
31 4.999567074377685
32 4.999563391484073
33 4.999559645195322
34 4.999555833858731
35 4.999551955763615
36 4.9995480091387545
37 4.999543992149679
38 4.9995399028958305
39 4.999535739407551
40 4.999531499642915
41 4.999527181484381
42 4.999522782735269
43 4.999518301116014
44 4.9995137342602245
45 4.999509079710506
46 4.9995043349140555
47 4.99949949721796
48 4.999494563864264
49 4.999489531984704
50 4.999484398595142
51 4.9994791605896465
52 4.99947381473423
53 4.999468357660158
54 4.999462785856868
55 4.999457095664426
56 4.999451283265493
57 4.999445344676766
58 4.999439275739862
59 4.999433072111588
60 4.99942672925356
61 4.999420242421108
62 4.99941360665142
63 4.99940681675086
64 4.999399867281387
65 4.999392752545998
66 4.999385466573139
67 4.999378003099951
68 4.999370355554286
69 4.999362517035381
70 4.999354480293044
71 4.9993462377052635
72 4.9993377812540505
73 4.999329102499388
74 4.999320192551083
75 4.999311042038357
76 4.9993016410769044
77 4.999291979233242
78 4.999282045486015
79 4.999271828183996
80 4.999261315000443
81 4.999250492883406
82 4.9992393480016055
83 4.999227865685373
84 4.999216030362144
85 4.999203825485908
86 4.999191233459934
87 4.999178235552006
88 4.999164811801339
89 4.999150940916169
90 4.999136600160936
91 4.999121765231786
92 4.999106410118969
93 4.999090506954497
94 4.999074025843171
95 4.999056934674837
96 4.999039198915376
97 4.9990207813735905
98 4.999001641940642
99 4.998981737298234
100 4.998961020591049
101 4.998939441058246
102 4.998916943617896
103 4.9988934683972355
104 4.998868950200255
105 4.998843317902721
106 4.99881649376275
107 4.998788392632926
108 4.998758921057109
109 4.998727976231793
110 4.99869544480769
111 4.998661201502128
112 4.998625107486495
113 4.998587008504983
114 4.998546732670955
115 4.998504087874586
116 4.998458858719377
117 4.99841080288457
118 4.998359646783954
119 4.998305080357004
120 4.998246750783192
121 4.998184254850546
122 4.9981171296300335
123 4.998044841000284
124 4.997966769421766
125 4.997882192159529
126 4.997790260875847
127 4.997689973122694
128 4.997580135705642
129 4.997459317081813
130 4.997325784763834
131 4.99717742191828
132 4.997011614623399
133 4.996825097002949
134 4.99661373467003
135 4.996372215797918
136 4.996093600373848
137 4.995768645466805
138 4.995384765069489
139 4.994924370977535
140 4.994362118215201
141 4.9936601079357334
142 4.992759034071528
143 4.991560621264983
144 4.989889412030912
145 4.987398685676694
146 4.983294393247612
147 4.975267454200382
148 4.95239498715875
149 8.957433075374608
150 4.991490365166151
151 4.979383290109275
152 3.2776627169886954
153 4.9764066253314905
154 4.958886581563313
155 4.827617334178019
156 1.0890005519375376
157 4.245759105592596
158 0.8094541286664461
159 0.9292633745987748
160 3.1349890719538567
161 2.394421071775107
162 0.9312609186615776
163 2.044827699402875
164 1.1176924694617638
165 0.1235712938846057
166 0.1123034655492824
167 1.2275579758521638
168 0.1837586541466345
169 0.7775679767022485
170 0.9877995123093493
171 0.8198966811311582
172 0.06145951789532408
173 0.021226549009461207
174 0.019825260595952958
175 0.019378351733832122
176 0.018953710407036407
177 0.018548127432772635
178 0.01816038740605137
179 0.017789376500865258
180 0.017434066294630797
181 0.01709350585444989
182 0.01676681487845981
183 0.016453177635338736
184 0.01615183754805421
185 0.015862092313934803
186 0.01558328948303107
187 0.015314822436324104
188 0.015056126718304426
189 0.014806676687163883
190 0.014565982451856163
191 0.014333587069562594
192 0.014109063980281276
193 0.013892014657733272
194 0.013682066457788244
195 0.0134788706473221
196 0.013282100597901868
197 0.01309145013003073
198 0.01290663199489266
199 0.012727376481645099
200 0.012553430139326627
201 0.012384554603391051
202 0.012220525517738825
203 0.012061131543925265
204 0.011906173449950099
205 0.011755463271715132
206 0.011608823540849062
207 0.011466086573168194
208 0.011327093812553141
209 0.01119169522549874
210 0.011059748742015488
211 0.010931119738956994
212 0.01080568056219986
213 0.010683310084422897
214 0.010563893295526922
215 0.010447320923001553
216 0.010333489079783247
217 0.010222298937370176
218 0.010113656422154775
219 0.010007471933115632
220 0.009903660079171976
221 0.009802139434652758
222 0.009702832311465095
223 0.009605664546668473
224 0.009510565304272875
225 0.00941746689017693
226 0.009326304579255335
227 0.009237016453686556
228 0.00914954325168727
229 0.00906382822588902
230 0.008979817010654558
231 0.008897457497688705
232 0.00881669971934968
233 0.008737495739115236
234 0.0086597995487008
235 0.008583566971366039
236 0.008508755570981559
237 0.008435324566463428
238 0.008363234751209583
239 0.008292448417202839
240 0.008222929283469125
241 0.008154642428602518
242 0.008087554227092494
243 0.008021632289204241
244 0.00795684540418535
245 0.007893163486585125
246 0.007830557525490672
247 0.007768999536496084
248 0.00770846251623486
249 0.0076489203993180144
250 0.007590348017530173
251 0.007532721061146577
252 0.007476016042244621
253 0.007420210259889022
254 0.007365281767082111
255 0.007311209339373608
256 0.0072579724450345506
257 0.007205551216704909
258 0.0071539264244301565
259 0.007103079450008052
260 0.0070529922625722895
261 0.00700364739534297
262 0.006955027923479974
263 0.006907117442978423
264 0.006859900050548467
265 0.006813360324427714
266 0.006767483306074398
267 0.006722254482695615
268 0.006677659770565821
269 0.006633685499093846
270 0.006590318395599957
271 0.006547545570765945
272 0.006505354504723591
273 0.006463733033748845
274 0.006422669337531421
275 0.006382151926990534
276 0.006342169632609843
277 0.006302711593265094
278 0.006263767245521897
279 0.0062253263133780976
280 0.006187378798432278
281 0.006149914970454844
282 0.006112925358344701
283 0.006076400741452075
284 0.006040332141250373
285 0.006004710813341007
286 0.005969528239775607
287 0.005934776121680199
288 0.005900446372169277
289 0.005866531109534142
290 0.005833022650695524
291 0.005799913504906439
292 0.005767196367695634
293 0.005734864115040399
294 0.005702909797758226
295 0.005671326636108463
296 0.0056401080145941015
297 0.005609247476955731
298 0.005578738721348607
299 0.005548575595696027
300 0.00551875209321009
301 0.005489262348074576
302 0.005460100631281382
303 0.005431261346615276
304 0.0054027390267803455
305 0.005374528329662666
306 0.005346624034722761
307 0.005319021039513928
308 0.005291714356319919
309 0.005264699108908163
310 0.005237970529393667
311 0.005211523955208688
312 0.005185354826174872
313 0.005159458681673114
314 0.005133831157907626
315 0.005108467985260627
316 0.00508336498573384
317 0.005058518070473906
318 0.005033923237378058
319 0.005009576568777461
320 0.00498547422919447
321 0.004961612463172646
322 0.004937987593174625
323 0.004914596017547349
324 0.0048914342085507
325 0.004868498710448182
326 0.004845786137656779
327 0.004823293172954208
328 0.004801016565741252
329 0.004778953130357267
330 0.004757099744447154
331 0.0047354533473775
332 0.004714010938700778
333 0.004692769576665293
334 0.004671726376769771
335 0.004650878510360667
336 0.0046302232032709115
337 0.004609757734498751
338 0.004589479434924936
339 0.0045693856860674256
340 0.004549473918871961
341 0.0045297416125375115
342 0.004510186293375202
343 0.004490805533699967
344 0.004471596950753423
345 0.004452558205657253
346 0.0044336870023959
347 0.004414981086827673
348 0.004396438245723289
349 0.004378056305831272
350 0.004359833132968635
351 0.004341766631136865
352 0.004323854741661858
353 0.004306095442357148
354 0.004288486746709892
355 0.004271026703088425
356 0.004253713393971537
357 0.004236544935197706
358 0.004219519475234674
359 0.0042026351944679605
360 0.004185890304508312
361 0.004169283047517363
362 0.004152811695550215
363 0.004136474549915991
364 0.004120269940553974
365 0.004104196225426443
366 0.004088251789926761
367 0.004072435046302324
368 0.004056744433092639
369 0.004041178414581002
370 0.004025735480260396
371 0.0040104141443126256
372 0.003995212945100273
373 0.003980130444671288
374 0.003965165228276036
375 0.003950315903895938
376 0.003935581101783871
377 0.003920959474015486
378 0.003906449694051797
379 0.0038920504563118748
380 0.0038777604757563606
381 0.0038635784874805263
382 0.003849503246317161
383 0.0038355335264489096
384 0.003821668121030147
385 0.0038079058418169615
386 0.003794245518806513
387 0.003780685999884645
388 0.003767226150481533
389 0.0037538648532356085
390 0.003740601007664781
391 0.003727433529845868
392 0.0037143613521007676
393 0.0037013834226902525
394 0.0036884987055142535
395 0.003675706179819411
396 0.0036630048399129847
397 0.0036503936948830465
398 0.0036378717683253083
399 0.0036254380980756807
400 0.003613091735948969
401 0.0036008317474833253
402 0.0035886572116902164
403 0.0035765672208100405
404 0.0035645608800729425
405 0.0035526373074650595
406 0.0035407956334995243
407 0.0035290350009926042
408 0.0035173545648447117
409 0.003505753491826002
410 0.003494230960366628
411 0.0034827861603513913
412 0.0034714182929187474
413 0.003460126570264197
414 0.0034489102154477017
415 0.0034377684622051066
416 0.003426700554763532
417 0.0034157057476608774
418 0.003404783305568512
419 0.003393932503118135
420 0.0033831526247320373
421 0.0033724429644567946
422 0.00336180282580038
423 0.0033512315215727504
424 0.0033407283737293325
425 0.0033302927132181277
426 0.0033199238798295185
427 0.003309621222049298
428 0.00329938409691461
429 0.003289211869872658
430 0.003279103914642397
431 0.003269059613078876
432 0.0032590783550402675
433 0.0032491595382574522
434 0.003239302568206321
435 0.003229506857982443
436 0.003219771828178194
437 0.003210096906762362
438 0.00320048152896195
439 0.0031909251371463002
440 0.003181427180713634
441 0.003171987115979408
442 0.003162604406067128
443 0.0031532785208010852
444 0.0031440089366010903
445 0.0031347951363794014
446 0.003125636609439347
447 0.0031165328513760157
448 0.0031074833639787606
449 0.0030984876551354993
450 0.0030895452387389197
451 0.0030806556345940534
452 0.003071818368328162
453 0.0030630329713018135
454 0.003054298980521663
455 0.0030456159385549328
456 0.0030369833934455726
457 0.003028400898631521
458 0.003019868012863941
459 0.003011384300127733
460 0.003002949329563291
461 0.002994562675389996
462 0.0029862239168308735
463 0.0029779326380385968
464 0.002969688428022908
465 0.0029614908805792642
466 0.0029533395942188305
467 0.0029452341720994624
468 0.0029371742219582346
469 0.002929159356044892
470 0.002921189191056704
471 0.0029132633480741217
472 0.0029053814524979127
473 0.0028975431339871827
474 0.002889748026398395
475 0.0028819957677257146
476 0.0028742860000420985
477 0.0028666183694415854
478 0.0028589925259824376
479 0.00285140812363128
480 0.0028438648202083884
481 0.002836362277333433
482 0.002828900160372721
483 0.0028214781383869188
484 0.0028140958840797057
485 0.0028067530737474413
486 0.0027994493872296306
487 0.0027921845078599907
488 0.002784958122418669
489 0.002777769921085038
490 0.0027706195973912426
491 0.002763506848176661
492 0.0027564313735430777
493 0.002749392876810381
494 0.0027423910644734035
495 0.0027354256461589034
496 0.002728496334583747
497 0.002721602845513599
498 0.002714744897722119
499 0.002707922212950961
0 4.9920656591522965
1 4.9905722478260195
2 4.988387790886223
3 4.984889976735901
4 4.978387918367483
5 4.962040322131133
6 5.058997945156312
7 4.999639925453628
8 4.999637384313639
9 4.999634806938728
10 4.999632192547506
11 4.999629540335944
12 4.999626849476545
13 4.999624119117483
14 4.999621348381703
15 4.99961853636598
16 4.9996156821399325
17 4.9996127847449925
18 4.999609843193338
19 4.999606856466757
20 4.999603823515481
21 4.999600743256945
22 4.999597614574496
23 4.999594436316044
24 4.999591207292641
25 4.999587926277004
26 4.999584592001944
27 4.999581203158736
28 4.999577758395406
29 4.9995742563149275
30 4.9995706954733246
31 4.999567074377685
32 4.999563391484073
33 4.999559645195322
34 4.999555833858731
35 4.999551955763615
36 4.9995480091387545
37 4.999543992149679
38 4.9995399028958305
39 4.999535739407551
40 4.999531499642915
41 4.999527181484381
42 4.999522782735269
43 4.999518301116014
44 4.9995137342602245
45 4.999509079710506
46 4.9995043349140555
47 4.99949949721796
48 4.999494563864264
49 4.999489531984704
50 4.999484398595142
51 4.9994791605896465
52 4.99947381473423
53 4.999468357660158
54 4.999462785856868
55 4.999457095664426
56 4.999451283265493
57 4.999445344676766
58 4.999439275739862
59 4.999433072111588
60 4.99942672925356
61 4.999420242421108
62 4.99941360665142
63 4.99940681675086
64 4.999399867281387
65 4.999392752545998
66 4.999385466573139
67 4.999378003099951
68 4.999370355554286
69 4.999362517035381
70 4.999354480293044
71 4.9993462377052635
72 4.9993377812540505
73 4.999329102499388
74 4.999320192551083
75 4.999311042038357
76 4.9993016410769044
77 4.999291979233242
78 4.999282045486015
79 4.999271828183996
80 4.999261315000443
81 4.999250492883406
82 4.9992393480016055
83 4.999227865685373
84 4.999216030362144
85 4.999203825485908
86 4.999191233459934
87 4.999178235552006
88 4.999164811801339
89 4.999150940916169
90 4.999136600160936
91 4.999121765231786
92 4.999106410118969
93 4.999090506954497
94 4.999074025843171
95 4.999056934674837
96 4.999039198915376
97 4.9990207813735905
98 4.999001641940642
99 4.998981737298234
100 4.998961020591049
101 4.998939441058246
102 4.998916943617896
103 4.9988934683972355
104 4.998868950200255
105 4.998843317902721
106 4.99881649376275
107 4.998788392632926
108 4.998758921057109
109 4.998727976231793
110 4.99869544480769
111 4.998661201502128
112 4.998625107486495
113 4.998587008504983
114 4.998546732670955
115 4.998504087874586
116 4.998458858719377
117 4.99841080288457
118 4.998359646783954
119 4.998305080357004
120 4.998246750783192
121 4.998184254850546
122 4.9981171296300335
123 4.998044841000284
124 4.997966769421766
125 4.997882192159529
126 4.997790260875847
127 4.997689973122694
128 4.997580135705642
129 4.997459317081813
130 4.997325784763834
131 4.99717742191828
132 4.997011614623399
133 4.996825097002949
134 4.99661373467003
135 4.996372215797918
136 4.996093600373848
137 4.995768645466805
138 4.995384765069489
139 4.994924370977535
140 4.994362118215201
141 4.9936601079357334
142 4.992759034071528
143 4.991560621264983
144 4.989889412030912
145 4.987398685676694
146 4.983294393247612
147 4.975267454200382
148 4.95239498715875
149 8.957433075374608
150 4.991490365166151
151 4.979383290109275
152 3.2776627169886954
153 4.9764066253314905
154 4.958886581563313
155 4.827617334178019
156 1.0890005519375376
157 4.245759105592596
158 0.8094541286664461
159 0.9292633745987748
160 3.1349890719538567
161 2.394421071775107
162 0.9312609186615776
163 2.044827699402875
164 1.1176924694617638
165 0.1235712938846057
166 0.1123034655492824
167 1.2275579758521638
168 0.1837586541466345
169 0.7775679767022485
170 0.9877995123093493
171 0.8198966811311582
172 0.06145951789532408
173 0.021226549009461207
174 0.019825260595952958
175 0.019378351733832122
176 0.018953710407036407
177 0.018548127432772635
178 0.01816038740605137
179 0.017789376500865258
180 0.017434066294630797
181 0.01709350585444989
182 0.01676681487845981
183 0.016453177635338736
184 0.01615183754805421
185 0.015862092313934803
186 0.01558328948303107
187 0.015314822436324104
188 0.015056126718304426
189 0.014806676687163883
190 0.014565982451856163
191 0.014333587069562594
192 0.014109063980281276
193 0.013892014657733272
194 0.013682066457788244
195 0.0134788706473221
196 0.013282100597901868
197 0.01309145013003073
198 0.01290663199489266
199 0.012727376481645099
200 0.012553430139326627
201 0.012384554603391051
202 0.012220525517738825
203 0.012061131543925265
204 0.011906173449950099
205 0.011755463271715132
206 0.011608823540849062
207 0.011466086573168194
208 0.011327093812553141
209 0.01119169522549874
210 0.011059748742015488
211 0.010931119738956994
212 0.01080568056219986
213 0.010683310084422897
214 0.010563893295526922
215 0.010447320923001553
216 0.010333489079783247
217 0.010222298937370176
218 0.010113656422154775
219 0.010007471933115632
220 0.009903660079171976
221 0.009802139434652758
222 0.009702832311465095
223 0.009605664546668473
224 0.009510565304272875
225 0.00941746689017693
226 0.009326304579255335
227 0.009237016453686556
228 0.00914954325168727
229 0.00906382822588902
230 0.008979817010654558
231 0.008897457497688705
232 0.00881669971934968
233 0.008737495739115236
234 0.0086597995487008
235 0.008583566971366039
236 0.008508755570981559
237 0.008435324566463428
238 0.008363234751209583
239 0.008292448417202839
240 0.008222929283469125
241 0.008154642428602518
242 0.008087554227092494
243 0.008021632289204241
244 0.00795684540418535
245 0.007893163486585125
246 0.007830557525490672
247 0.007768999536496084
248 0.00770846251623486
249 0.0076489203993180144
250 0.007590348017530173
251 0.007532721061146577
252 0.007476016042244621
253 0.007420210259889022
254 0.007365281767082111
255 0.007311209339373608
256 0.0072579724450345506
257 0.007205551216704909
258 0.0071539264244301565
259 0.007103079450008052
260 0.0070529922625722895
261 0.00700364739534297
262 0.006955027923479974
263 0.006907117442978423
264 0.006859900050548467
265 0.006813360324427714
266 0.006767483306074398
267 0.006722254482695615
268 0.006677659770565821
269 0.006633685499093846
270 0.006590318395599957
271 0.006547545570765945
272 0.006505354504723591
273 0.006463733033748845
274 0.006422669337531421
275 0.006382151926990534
276 0.006342169632609843
277 0.006302711593265094
278 0.006263767245521897
279 0.0062253263133780976
280 0.006187378798432278
281 0.006149914970454844
282 0.006112925358344701
283 0.006076400741452075
284 0.006040332141250373
285 0.006004710813341007
286 0.005969528239775607
287 0.005934776121680199
288 0.005900446372169277
289 0.005866531109534142
290 0.005833022650695524
291 0.005799913504906439
292 0.005767196367695634
293 0.005734864115040399
294 0.005702909797758226
295 0.005671326636108463
296 0.0056401080145941015
297 0.005609247476955731
298 0.005578738721348607
299 0.005548575595696027
300 0.00551875209321009
301 0.005489262348074576
302 0.005460100631281382
303 0.005431261346615276
304 0.0054027390267803455
305 0.005374528329662666
306 0.005346624034722761
307 0.005319021039513928
308 0.005291714356319919
309 0.005264699108908163
310 0.005237970529393667
311 0.005211523955208688
312 0.005185354826174872
313 0.005159458681673114
314 0.005133831157907626
315 0.005108467985260627
316 0.00508336498573384
317 0.005058518070473906
318 0.005033923237378058
319 0.005009576568777461
320 0.00498547422919447
321 0.004961612463172646
322 0.004937987593174625
323 0.004914596017547349
324 0.0048914342085507
325 0.004868498710448182
326 0.004845786137656779
327 0.004823293172954208
328 0.004801016565741252
329 0.004778953130357267
330 0.004757099744447154
331 0.0047354533473775
332 0.004714010938700778
333 0.004692769576665293
334 0.004671726376769771
335 0.004650878510360667
336 0.0046302232032709115
337 0.004609757734498751
338 0.004589479434924936
339 0.0045693856860674256
340 0.004549473918871961
341 0.0045297416125375115
342 0.004510186293375202
343 0.004490805533699967
344 0.004471596950753423
345 0.004452558205657253
346 0.0044336870023959

In [ ]:
print(coef)

[-2.0530323544521973, 3.8669948081557455, -6.05662706783513]
[-2.0530323544521973, 3.8669948081557455, -6.05662706783513]

In [ ]:
for row in data:
  print(row[2] , ' ***  ' , predict_val(row,coef), ' *** ' , round(predict_val(row,coef)))

0.0  ***   0.04157372933026011  ***  0
0.0  ***   9.858877791695048e-07  ***  0
0.0  ***   8.335169377758767e-08  ***  0
0.0  ***   0.00012632997368335012  ***  0
0.0  ***   2.6432977227614324e-05  ***  0
1.0  ***   0.9997527482128017  ***  1
1.0  ***   0.9786699376093694  ***  1
1.0  ***   0.9999807132660437  ***  1
1.0  ***   0.9999999999982796  ***  1
1.0  ***   0.981318395627942  ***  1
0.0  ***   0.04157372933026011  ***  0
0.0  ***   9.858877791695048e-07  ***  0
0.0  ***   8.335169377758767e-08  ***  0
0.0  ***   0.00012632997368335012  ***  0
0.0  ***   2.6432977227614324e-05  ***  0
1.0  ***   0.9997527482128017  ***  1
1.0  ***   0.9786699376093694  ***  1
1.0  ***   0.9999807132660437  ***  1
1.0  ***   0.9999999999982796  ***  1
1.0  ***   0.981318395627942  ***  1

**Data for diabetic predictions**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/diabetes-dataset.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0

In [ ]:
df['Outcome'].unique()

array([1, 0])

In [ ]:
df['Outcome'].value_counts()

0    1316
1     684
Name: Outcome, dtype: int64

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.shape

(2000, 9)

In [ ]:
(df == 0).sum()

Pregnancies                  301
Glucose                       13
BloodPressure                 90
SkinThickness                573
Insulin                      956
BMI                           28
DiabetesPedigreeFunction       0
Age                            0
Outcome                     1316
dtype: int64

In [ ]:
x = df.drop('Outcome' , axis='columns')
y = df['Outcome']

In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_res, y_res = ros.fit_resample(x, y)

In [ ]:
y_res.value_counts()

1    1316
0    1316
Name: Outcome, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X_res, y_res, train_size=0.8)

In [ ]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()

model1.fit(xtrain,ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
#Evaluate

accTrain = (ytrain == model1.predict(xtrain)).sum()/len(xtrain)
print(accTrain)

0.744418052256532

In [ ]:
model1.score(xtrain,ytrain)

0.744418052256532

In [ ]:
accTest = model1.score(xtest,ytest)
print(accTest)

0.7362428842504743

**Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytrain , model1.predict(xtrain))

array([[803, 250],
       [288, 764]])

In [ ]:
confusion_matrix(ytest , model1.predict(xtest))

array([[199,  64],
       [ 75, 189]])

**Customer Churn Classifications**

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/customer_churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df1 = df.drop('customerID' , axis = 'columns')
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df1.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df1.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
def fix_totalcharges(x):
  try:
    return float(x)
  except:
    return np.nan

In [ ]:
df1['TotalCharges'] = df1['TotalCharges'].apply(fix_totalcharges)

In [ ]:
df1.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [ ]:
df1.shape

(7043, 20)

In [ ]:
df2 = df1.dropna(axis='rows')
df2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df2.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [ ]:
non_num = []
for col in df2.columns:
  if (df2[col].dtype == object):
    non_num.append(col)

In [ ]:
print(non_num)

['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']

In [ ]:
for cols in non_num:
  print(cols , df2[cols].unique())

gender ['Female' 'Male']
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
PhoneService ['No' 'Yes']
MultipleLines ['No phone service' 'No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes' 'No internet service']
OnlineBackup ['Yes' 'No' 'No internet service']
DeviceProtection ['No' 'Yes' 'No internet service']
TechSupport ['No' 'Yes' 'No internet service']
StreamingTV ['No' 'Yes' 'No internet service']
StreamingMovies ['No' 'Yes' 'No internet service']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn ['No' 'Yes']

In [ ]:
def fix_yes_no(x):
  if x == 'Yes':
    return 'Yes'
  else:
    return 'No'

In [ ]:
df2['MultipleLines'] = df2['MultipleLines'].apply(fix_yes_no)
df2['OnlineSecurity'] = df2['OnlineSecurity'].apply(fix_yes_no)
df2['OnlineBackup'] = df2['OnlineBackup'].apply(fix_yes_no)
df2['DeviceProtection'] = df2['DeviceProtection'].apply(fix_yes_no)
df2['TechSupport'] = df2['TechSupport'].apply(fix_yes_no)
df2['StreamingTV'] = df2['StreamingTV'].apply(fix_yes_no)
df2['StreamingMovies'] = df2['StreamingMovies'].apply(fix_yes_no)

<ipython-input-15-72faabdbf292>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['MultipleLines'] = df2['MultipleLines'].apply(fix_yes_no)
<ipython-input-15-72faabdbf292>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['OnlineSecurity'] = df2['OnlineSecurity'].apply(fix_yes_no)
<ipython-input-15-72faabdbf292>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['OnlineBackup'] = df2['OnlineBackup'].apply(fix_yes_no)
<ipython-input-15-72faabdbf292>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['DeviceProtection'] = df2['DeviceProtection'].apply(fix_yes_no)
<ipython-input-15-72faabdbf292>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['TechSupport'] = df2['TechSupport'].apply(fix_yes_no)
<ipython-input-15-72faabdbf292>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['StreamingTV'] = df2['StreamingTV'].apply(fix_yes_no)
<ipython-input-15-72faabdbf292>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['StreamingMovies'] = df2['StreamingMovies'].apply(fix_yes_no)

In [ ]:
for cols in non_num:
  print(cols , df2[cols].unique())

gender ['Female' 'Male']
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
PhoneService ['No' 'Yes']
MultipleLines ['No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes']
OnlineBackup ['Yes' 'No']
DeviceProtection ['No' 'Yes']
TechSupport ['No' 'Yes']
StreamingTV ['No' 'Yes']
StreamingMovies ['No' 'Yes']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn ['No' 'Yes']

In [ ]:
for cols in non_num:
  print(cols , df2[cols].value_counts())
  print('******************')

gender Male      3549
Female    3483
Name: gender, dtype: int64
******************
Partner No     3639
Yes    3393
Name: Partner, dtype: int64
******************
Dependents No     4933
Yes    2099
Name: Dependents, dtype: int64
******************
PhoneService Yes    6352
No      680
Name: PhoneService, dtype: int64
******************
MultipleLines No     4065
Yes    2967
Name: MultipleLines, dtype: int64
******************
InternetService Fiber optic    3096
DSL            2416
No             1520
Name: InternetService, dtype: int64
******************
OnlineSecurity No     5017
Yes    2015
Name: OnlineSecurity, dtype: int64
******************
OnlineBackup No     4607
Yes    2425
Name: OnlineBackup, dtype: int64
******************
DeviceProtection No     4614
Yes    2418
Name: DeviceProtection, dtype: int64
******************
TechSupport No     4992
Yes    2040
Name: TechSupport, dtype: int64
******************
StreamingTV No     4329
Yes    2703
Name: StreamingTV, dtype: int64
******************
StreamingMovies No     4301
Yes    2731
Name: StreamingMovies, dtype: int64
******************
Contract Month-to-month    3875
Two year          1685
One year          1472
Name: Contract, dtype: int64
******************
PaperlessBilling Yes    4168
No     2864
Name: PaperlessBilling, dtype: int64
******************
PaymentMethod Electronic check             2365
Mailed check                 1604
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: PaymentMethod, dtype: int64
******************
Churn No     5163
Yes    1869
Name: Churn, dtype: int64
******************

In [ ]:
df2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
#One hot encoding
pd.get_dummies(df2['gender'])

      Female  Male
0          1     0
1          0     1
2          0     1
3          0     1
4          1     0
...      ...   ...
7038       0     1
7039       1     0
7040       1     0
7041       0     1
7042       0     1

[7032 rows x 2 columns]

In [ ]:
non_num_data = df2[non_num].drop('Churn' , axis='columns')
non_num_data.head()

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,Female,Yes,No,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check
1,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check
2,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
3,Male,No,No,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic)
4,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check

In [ ]:
encoded_non_num = pd.get_dummies(non_num_data)
encoded_non_num.head()

,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,MultipleLines_No,MultipleLines_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,0,1,1,0,1,0,1,0,...,0,1,0,0,0,1,0,0,1,0
1,0,1,1,0,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,0,1
2,0,1,1,0,1,0,0,1,1,0,...,0,1,0,0,0,1,0,0,0,1
3,0,1,1,0,1,0,1,0,1,0,...,0,0,1,0,1,0,1,0,0,0
4,1,0,1,0,1,0,0,1,1,0,...,0,1,0,0,0,1,0,0,1,0

In [ ]:
df2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df3 = df2.drop(non_num , axis='columns')
df3.head()

   SeniorCitizen  tenure  MonthlyCharges  TotalCharges
0              0       1           29.85         29.85
1              0      34           56.95       1889.50
2              0       2           53.85        108.15
3              0      45           42.30       1840.75
4              0       2           70.70        151.65

In [ ]:
X = pd.concat((df3,encoded_non_num) , axis = 'columns')
X.head()         #Features

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,1,0,0,1,1,0,...,0,1,0,0,0,1,0,0,1,0
1,0,34,56.95,1889.50,0,1,1,0,1,0,...,0,0,1,0,1,0,0,0,0,1
2,0,2,53.85,108.15,0,1,1,0,1,0,...,0,1,0,0,0,1,0,0,0,1
3,0,45,42.30,1840.75,0,1,1,0,1,0,...,0,0,1,0,1,0,1,0,0,0
4,0,2,70.70,151.65,1,0,1,0,1,0,...,0,1,0,0,0,1,0,0,1,0

In [ ]:
Y = df2['Churn'].map({'No' :0 , 'Yes' : 1})
Y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7032, dtype: int64

In [ ]:
Y.value_counts()

0    5163
1    1869
Name: Churn, dtype: int64

In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_res, Y_res = ros.fit_resample(X, Y)

**Split, Import algorithm and train the model**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(X_res , Y_res , train_size=0.80)

model2 = LogisticRegression()

model2.fit(xtrain,ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
print(model2.score(xtrain,ytrain))
print(model2.score(xtest,ytest))

0.7653753026634382
0.771539206195547

In [ ]:
confusion_matrix(ytrain , model2.predict(xtrain))

array([[2992, 1116],
       [ 822, 3330]])

In [ ]:
confusion_matrix(ytest , model2.predict(xtest))

array([[774, 281],
       [191, 820]])

**Predictions**

In [ ]:
df2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
gender = 'Male'
senior_citizen = 0
partner = "Yes"
dependents = "No"
tenure = 24
phoneservice = "Yes"
multiplelines = "No"
internetservice = "DSL"
onlinesecurity = "No"
onlinebackup = "Yes"
deviceprotection = "No"
techsupport = "Yes"
streamingtv = "No"
streamingmovies = "Yes"
contract = "One year"
paperlessbilling = "Yes"
paymentmethod = "Electronic check"
monthlycharges = 70.70
totalcharges = 1880

In [ ]:
#features used for training the model
xtrain.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [ ]:
len(xtrain.columns)

38

In [ ]:
input = np.zeros(len(xtrain.columns))
input

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [ ]:
input[0] = senior_citizen
input[1] = tenure
input[2] = monthlycharges
input[3] = totalcharges

print(input)

[   0.    24.    70.7 1880.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.     0.     0. ]

In [ ]:
'gender_'+gender
list(xtrain.columns).index('gender_'+gender)     #=> 5 indicates 5th column represents Male customers
input[5] = 1
print(input)

[0.00e+00 2.40e+01 7.07e+01 1.88e+03 0.00e+00 1.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]

In [ ]:
'Partner_'+partner
input[list(xtrain.columns).index('Partner_'+partner)] = 1
print(input)

[0.00e+00 2.40e+01 7.07e+01 1.88e+03 0.00e+00 1.00e+00 0.00e+00 1.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]

In [ ]:
'Dependents_'+dependents
input[list(xtrain.columns).index('Dependents_'+dependents)] = 1
print(input)

[0.00e+00 2.40e+01 7.07e+01 1.88e+03 0.00e+00 1.00e+00 0.00e+00 1.00e+00
 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]

In [ ]:
xtrain.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [ ]:
input[list(xtrain.columns).index('PhoneService_'+phoneservice)] = 1
input[list(xtrain.columns).index('MultipleLines_'+multiplelines)] = 1
input[list(xtrain.columns).index('InternetService_'+internetservice)] = 1
input[list(xtrain.columns).index('OnlineSecurity_'+onlinesecurity)] = 1
input[list(xtrain.columns).index('OnlineBackup_'+onlinebackup)] = 1
input[list(xtrain.columns).index('DeviceProtection_'+deviceprotection)] = 1
input[list(xtrain.columns).index('TechSupport_'+techsupport)] = 1
input[list(xtrain.columns).index('StreamingTV_'+streamingtv)] = 1
input[list(xtrain.columns).index('Contract_'+contract)] = 1
input[list(xtrain.columns).index('PaperlessBilling_'+paperlessbilling)] = 1
input[list(xtrain.columns).index('PaymentMethod_'+paymentmethod)] = 1

In [ ]:
print(input)

[0.00e+00 2.40e+01 7.07e+01 1.88e+03 0.00e+00 1.00e+00 0.00e+00 1.00e+00
 1.00e+00 0.00e+00 0.00e+00 1.00e+00 1.00e+00 0.00e+00 1.00e+00 0.00e+00
 0.00e+00 1.00e+00 0.00e+00 0.00e+00 1.00e+00 1.00e+00 0.00e+00 0.00e+00
 1.00e+00 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e+00 0.00e+00
 0.00e+00 1.00e+00 0.00e+00 0.00e+00 1.00e+00 0.00e+00]

In [ ]:
print(model2.predict([input]))

[0]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(